name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anaconda-anon-usage=0.7.4=pyhb46e38b_100
  - anaconda-auth=0.10.0=py313h06a4308_1
  - anaconda-cli-base=0.6.0=py313h06a4308_0
  - annotated-types=0.6.0=py313h06a4308_1
  - anyio=4.11.0=pyhcf101f3_0
  - archspec=0.2.5=pyhd3eb1b0_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py313h07c4f96_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - boltons=25.0.0=py313h06a4308_0
  - brotlicffi=1.0.9.2=py313hbdd6827_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py313h4eded50_1
  - charset-normalizer=3.4.4=py313h06a4308_0
  - click=8.1.8=py313h06a4308_0
  - comm=0.2.3=pyhe01879c_0
  - conda=25.9.1=py313h06a4308_0
  - conda-anaconda-telemetry=0.3.0=pyhd3eb1b0_1
  - conda-anaconda-tos=0.2.2=py313h06a4308_1
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhdf14ebd_1
  - conda-package-handling=2.4.0=py313h06a4308_1
  - conda-package-streaming=0.12.0=py313h06a4308_1
  - cpp-expected=1.1.0=hdb19cb5_0
  - cpython=3.13.9=py313hd8ed1ab_101
  - cryptography=46.0.3=py313h0a354b3_0
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.17=py313h5d5ffb9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distro=1.9.0=py313h06a4308_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h3385a95_0
  - fmt=11.2.0=hca5f364_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - frozendict=2.4.6=py313hee96239_0
  - gettext=0.21.0=hedfda30_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=py313h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jansson=2.14=h5eee18b_1
  - jaraco.classes=3.4.0=py313h06a4308_0
  - jaraco.context=6.0.0=py313h06a4308_0
  - jaraco.functools=4.1.0=py313h06a4308_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=3.0.0=py313h06a4308_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - keyring=25.6.0=py313h06a4308_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lark=1.3.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libarchive=3.8.2=h3ec8f01_0
  - libcurl=8.16.0=heebcbe5_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libmamba=2.3.2=h4368100_0
  - libmambapy=2.3.2=py313hea2f153_0
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.1=h697f920_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsolv=0.7.30=h6f1ccf3_2
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=4.0.0=py313h06a4308_0
  - markupsafe=3.0.3=py313h3dea7bd_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=py313h06a4308_0
  - menuinst=2.4.1=py313h06a4308_1
  - mistune=3.1.4=pyhcf101f3_0
  - more-itertools=10.8.0=py313h06a4308_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.11.2=h6a678d5_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=py313h06a4308_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.2=pyhc872135_1
  - pkce=1.0.3=py313h06a4308_0
  - platformdirs=4.5.0=py313h06a4308_0
  - pluggy=1.5.0=py313h06a4308_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py313h54dd161_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.23=py313h06a4308_0
  - pydantic=2.12.3=py313h06a4308_1
  - pydantic-core=2.41.4=py313h498d7c9_0
  - pydantic-settings=2.10.1=py313h06a4308_0
  - pygments=2.19.2=py313h06a4308_0
  - pyjwt=2.10.1=py313h06a4308_0
  - pysocks=1.7.1=py313h06a4308_1
  - python=3.13.9=h7e8bc2b_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.0=py313h06a4308_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.13.9=h4df99d1_101
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313h3dea7bd_0
  - pyzmq=27.1.0=py312hfb55c3c_0
  - readchar=4.2.1=py313h06a4308_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=pyhcf101f3_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.5=py313h06a4308_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.2.0=py313h06a4308_0
  - rpds-py=0.29.0=py313h843e2db_0
  - ruamel.yaml=0.18.16=py313h4aee224_0
  - ruamel.yaml.clib=0.2.14=py313h4aee224_0
  - secretstorage=3.4.0=py313h3e8c6aa_0
  - semver=3.0.4=py313h06a4308_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=py313h06a4308_0
  - shellingham=1.5.4=py313h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.5.0=pyhcf101f3_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py313h06a4308_0
  - tornado=6.5.2=py313h07c4f96_2
  - tqdm=4.67.1=py313h7040dfc_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.1=py313h06a4308_1
  - typer=0.17.4=py313h06a4308_0
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing-inspection=0.4.2=py313h06a4308_0
  - typing_extensions=4.15.0=py313h06a4308_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=py313h06a4308_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - yaml-cpp=0.8.0=h6a678d5_1
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.24.0=py313h3d778a8_0
  - zstd=1.5.7=h11fc155_0
prefix: /home/lampros/miniconda3
